apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops1
  template:
    metadata:
      labels:
        app: devops1
    spec:
      containers:
      - name: devops1-container
        image: your-dockerhub-username/devops1-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devops1-service
spec:
  type: NodePort
  selector:
    app: devops1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
